### ISSUE TITLE
Skrytá zbytečná závislost na Dibi

### ISSUE THREAD

**Issue by v6ak** [skaut/Skautis#16]
Třída `\SkautIS\Nette\Tracy\Panel` dědí z `\DibiObject`, což je skrytá závislost na Dibi, která není uvedena v composer.json.

Nicméně je to zřejmě jediná závislost na Dibi, navíc celkem zbytečná. Stačilo by místo `\DibiObject` použít `\Nette\Object` a mělo by to být v cajku.

**Comment by sinacek** [comment]
To mi uteklo, díky za upozornění, už jsem to opravil. https://github.com/sinacek/SkautIS/releases/tag/v1.2.2
