### ISSUE TITLE
Notice: neinicializované $s

### ISSUE THREAD

**Issue by v6ak** [skaut/Skautis#17]
Se zapnutým E_NOTICE to tady háže notice:

https://github.com/sinacek/SkautIS/blob/1ee8d2b71527040c445fb1f0872f0e381a0fee48/src/SkautIS/Nette/Tracy/Panel.php#L67

Chybí `$s=""`.

**Comment by sinacek** [comment]
Opraveno, díky. https://github.com/sinacek/SkautIS/blob/1.x/src/SkautIS/Nette/Tracy/Panel.php#L66
