### ISSUE TITLE
Trace nemusí obsahovat line

### ISSUE THREAD

**Issue by v6ak** [skaut/Skautis#18]
Nevím přesně okolnosti, za kterých to nastává, ale někdy se může stát, že trace neobsahuje index `'line'`. Potom to zde hodí E_NOTICE:

https://github.com/sinacek/SkautIS/blob/1ee8d2b71527040c445fb1f0872f0e381a0fee48/src/SkautIS/Nette/Tracy/Panel.php#L91

**Comment by sinacek** [comment]
Opravil jsem to a zrušil jsem posun řádkování. Nevím proč mi to předtím vycházelo, že by tam být mělo. https://github.com/sinacek/SkautIS/commit/f1f9a35b968730aee451fe887200bda85fecf230

**Comment by v6ak** [comment]
Výraz `($f['line'] !== NULL ? ": " . $f['line'] : "")` bohužel stále skončí s E_NOTICE, pokud $f['line'] neexistuje. Ukázka:

```
% cat x.php 
<?php
$f = [];
echo ($f['line'] !== NULL ? ": " . $f['line'] : "");
% php x.php 
PHP Notice:  Undefined index: line in /tmp/y/x.php on line 3
PHP Stack trace:
PHP   1. {main}() /tmp/y/x.php:0
```

Na to lze použít isset(...), tedy třeba `(isset($f['line']) ? ": " . $f['line'] : "")`.

**Comment by sinacek** [comment]
Poslal jsem na server jine reseni nez jsem chtel. Udelal jsem Amend a je to tam přes array_key_exists https://github.com/sinacek/SkautIS/commit/2bad6677ea46ef3e31ac68a7d9844a4beb9a90b4#diff-696c125bd7faf717969e304e30a89addR90
