### ISSUE TITLE
Session Storage problem

### ISSUE THREAD

**Issue by JindrichPilar** [skaut/Skautis#20]
Ahoj,

dostal jsem se do faze kdy potrebuji vyresit tento problem, ktery jsem uz nejakou dobu odkladal. Bohuzel nedari se mi prijit na elegantni zpusob se zachovanim zpetne kompatibility.

`$this->perStorage` ma z dob kdy tahle knihovna byla soucasti nejakeho Nette projektu par neuplne peknych vlastnosti. 
Ktere se spoustou popularnich tropi problemy, protoze nepouzivaji magicke metody. (Symfony, Laravel, CodeIgniter, CakePHP, FuelPHP, Aura) [alespon podle skouknuti dokumentace dokumentace]

Pristup k nedefinovanym promenym a spolehani se na PHP ze z nich automaticky udela pole.
[Kod](https://github.com/sinacek/SkautIS/blob/master/src/SkautIS/SkautIS.php#L198-L201)

Zpusob jakym aplikace pracuje se session vubec nemusi mit z defaultni PHP session nic spolecneho.
[Kod](https://github.com/sinacek/SkautIS/blob/master/src/SkautIS/SkautIS.php#L209)

Navrhovane reseni:
Vytvori se trida pro konfiguraci, ktera klidne muze implementovat ArrayAccess, ale `has(),get(),set()`  by bylo vhodnejsi. Ta trida bude implementovat Serializable interface.

Misto session dostane SkautIS  SessionAdapter s metodou `store('nazev', $object)` a `retrieve('nazev')`.  A s pomoci teto tridy vse ulozit v `__destruct()` metode. A naopak pri `__construct()` nacist.

Kdyz by se nejake zakladni adaptery pribalily do knihovny (pro $_SESSION a NETTE session treba) byly by nutne zmeny v kodu pro uzivatele knihovny minimalni.
Misto:

```
$storage = \Nette\Environment::getSession()->getSection("__" . __CLASS__);
$this->context->skautIS->setStorage($storage, TRUE);
```

By bylo

```
$section = \Nette\Environment::getSession()->getSection("__" . __CLASS__);
$storage = new \SkautIS\SessionAdapter\NetteAdapter($section);
$this->context->skautIS->setStorage($storage, TRUE);
```

Misto

```
$skautis = \SkautIS\SkautIS::getInstance()
```

By bylo

```
$skautis = \SkautIS\SkautIS::getInstance()
$storage = new \SkautIS\SessionAdapter\SessionAdapter();
$skautis->setStorage($storage);
```

Pres konfiguracni objekt je to vhodnejsi nez pristupovat primo k SessionAdapteru, protoze nektere implementace podporuji sekce a jine odlisnosti.

Reseni rad implementuji, ale nechtel jsem se do toho postet pred nejakou diskusi kdyz to neni zpetne kompatibilni.

**Comment by sinacek** [comment]
Ahoj,
nechceš u toho adaptéru udělat __set a __get místo store a retrive? Jsou to magicke metody, ale nepochopil jsme z toho, jestli i v tomhle případě by vadili. Pokud ano, tak bych je použil jen jako názvy metod, tedy set($name, $value) a get($name).

Jinak bych zkusil to udělat tak, aby to tam byl uz na začátku ten SessionAdapter nastaven jako výchozí, protože ne každý si chce hned na začátku zjištovat, jaký adapter je pro něj vhodný, čímž by se mohla zachovat i kompatibillita ne?

Obecně vítám všechny změny, které to zobecnují, jen bych chtěl zachovat možnost to používat hned po naistalování, aby to mohl používat i méně zkušený programátor.

**Comment by JindrichPilar** [comment]
Zalezi na tom podle ceho clovek urcuje jestli by vadily. Z pohledu "funguje ano/ne" by pri vyuziti v teto knihovne nevadily. Nicmene je nekolik faktoru proc to neni dobre pouziti.  Par je jich tady: 
http://stackoverflow.com/a/6184893  

`set($name, $value) a get($name)` muze byt. Ono je to jedno, uzivatel knihovny zavola pouze konstruktor, o techto metodach ani nemusi vedet.

SessionAdapter muze byt vychozi, zachova se kompatibilita se $_SESSION, uzivatele NETTE budou muset jeden radek pridat.

Aby byla funkci hned po nainstalovani, bylo by lepsi reseni mit knihovnu naprosto obecnou. A ktomu Factory co by ji sestavovala. Protoze uzivatel Frameworku X chce jinak knihovnu nez uzivatel Frameworku Y a clovek pouzivajici ciste PHP to chce zase jinak. Cimz by se dalo zbavit i toho Singletonu.

Momentalne pracuji na bundle pro Symfony ktery prave zprostredkovava instalaci funkcni ihned a to ze se knihovna snazi inicializovat sama to ztezuje.

**Comment by sinacek** [comment]
Jasně, byl bych pro to set a get, protože mi to prijdou nejobecnejsi nazvy.

Tu obecnou kompatibilitu bych směroval na použití čistě v PHP, protože tam podle mě bude největší % amatérských programátorů, kteří by si nevěděli s nastavením rady. 

Ten singleton: historicky mi přišlo, že aplikace se nebude chtít připojovat k více skautisům najednou a příjde mi to jako nejjednodušší užití pro plain php. Ve frameworku si to můžu někam navázat a nemusím se o to starat, ale u toho plain php bych to viděl jako komplikovanější když to nebude singleton. 

Jinak bych chtěl aby uživatele Nette to používali přes to rozšíření co jsem tedka dodělával, takže tam to změním já a ostatní už by nic měnit nemuseli. 

S tím sestavováním a factory: možná by šlo rozdělit class Skautis na dvě, kde první zůstane pod názevm Skautis a bude to stále singleton, ale bude se chovat jako faktory pro základní nastavení a pak bude nová třída "nenapadáMěJméno", kde bude ta logika současné class Skautis. Tím by se to opět zachovalo kompatibilní. Co ty na to?

Jinak pokud si metoda nastavi v konstruktoru storage na sessionAdapter a ty to hned potom změníš jak jsi psal, tak to by nemělo ničemu vadit ne?

**Comment by JindrichPilar** [comment]
Mozna by stalo za to udelat samostatny Nette balicek pouzivajici tuhle knihovnu.

Factory: ano, to by fungovalo dobre
Code:

```
namespace SkautIS;

class SkautIS
{
   protected static $instance = NULL;

    /**
     * Funkce pro ziskani SkautIS knihovny
     */
    public static function getInstance(...stejne parametry...) 
    {
        if ( is_null(self::$instance) ) {
            self::$instance = new SkautISLib(...stejne parametry...)
        }

        return self::$instance;
    }
}
```

```
namespace SkautIS;

class SkautISLib
{
  /// Code soucasne knihovny bez getInstance a s ``public __construct()``
}
```

Bylo by lepsi umoznit pridat Adapter hned do konstruktoru, aby se na $_SESSION vubec nesahalo. A hlavne z toho Adapteru chce nacist ulozene nastaveni.
Pokud bys nenastavil v konstruktoru `Adapter` a nastavil ho pozdeji pomoci `setAdapter`, muselo by se nejak vyresit (parametr `setAdapter`) nasledujici moznosti:
- Nacist ulozena data z nove pridaneho `Adapteru`
- Zkopirovat soucasny config z automaticky vytvoreneho `Adapteru` do noveho `Adapteru`
- Nedelat nic, jen pouzit novy `Adapter` pro ulozeni pri `__destruct`

**Comment by sinacek** [comment]
Samostatný balíček podle mě není potřeba, protože stačí, aby tady byla jedna složka, kde jsou všechny věci k Nette a jejich instalace do Nette je jednoduchá. Beru to jako drivery pro různé frameworky, takže klidně zde můžou být i další. Netříštil bych to, pokud se najde někdo, kdo se o daný "driver" bude starat.

Jinak StaticFactory je podle mě to, co by náš problém vyřešilo i se zachováním zpětné kompatibility. 

Jinak dokumentaci se snažím držet zatím pouze v [README.md](https://github.com/sinacek/SkautIS/blob/master/README.md), takže tam lze cokoli jednoduše doplnit.

Při změně Adapteru jsem očekával, že lze říct, které chování chci jestli zachovat data z [minuleho](https://github.com/sinacek/SkautIS/blob/master/src/SkautIS/SkautIS.php#L197) nebo jen použít nový. Ale jsem pro, aby šel zadat volitelně Adapter v konstruktoru "SkautISLib" a pokud tam nebude, tak použije ten SessionAdapter. Možností přidání do konstruktoru bych pak asi zrušil službu setAdapter, abychom nemuseli tam zbytečně řešit, kterou z možností transformace na nový adaptér chce použít a příjde mi to i jako zbytečné, protože podle mě by měl při zakládání vedět, jaký tam chce.

Nemáš nápad na nějaké lepší pojmenování pro SkautISLib? Napadlo mě SkautisControler, ale to asi taky není uplně ono. Chtěl bych tím vystihnout to, že se stará o další běh a řídí ho.

**Comment by JindrichPilar** [comment]
To vidim presne obracene. Mela by byt knihovna s co nejmene zavislostma. A potom by meli byt balicky pro frameworky ktere tu knihovnu pouzivaji. 
- Kdyz pouzivam Framwerok A nechci kod pro Framweroky A,B,C. (i kdyby jen kvuli mistu na disku)
- Nektere frameworky vyzaduji danou strukturu, takze to proste ani do podslozky dat nelze (Symfony)
- Takovy "driver" se muze rozrust do desitek  az stovek souboru
- Lepsi podpora pro starsi verze

Pekny priklad je tady: [Sylius](https://github.com/Sylius) Vzdy knihovna oddelena od frameworku, delajici veskerou logiku. A pak bundle jako tenka vrstva pripojujici knihovnu k frameworku.

**Comment by sinacek** [comment]
To, že je součástí nějaká složka podle mě nevytváří závislost. Překvapuje mě, že nějaký současný framework si neumí načíst jen třídy které potřebuje a ty ostatní by mu v nečem překáželi.

Příjde mi to v současné době trochu přehnaně velkolepé, ale v zásadě proč ne. Udělám nový repositář pro Nette a založím novou větev pro vývoj verze 2.0, kam by pak přišel Adapter aspol.

**Comment by JindrichPilar** [comment]
Nejde jen o nacteni trid. Autoloading ma uz kazdy. Je spousta dalsich veci ktere ani nemusi byt PHP kod. Napriklad css, javascript, obrazky nebo service definice(yaml, xml). 

Mozna to ted vypada prehnane, ale zkusenost mam takovou ze nejhorsi problemy byly z maleho decouplingu nez z velkeho.

Taky se muze zalozit GitHub organizace pro tyto veci, takze kdyz jeden maitainer odpadne muze ho zastoupit jiny.
