### ISSUE TITLE
Chybí example usecase

### ISSUE THREAD

**Issue by zbycz** [skaut/Skautis#3]
Mohl bys prosím doplnit nějaký ukázkový usecase? Třeba do /README.rst, pak se to hezky ukazuje při otevření repa. :-)  Mně osobně jde pouze o přihlášení uživatele a vypsání jeho Person.

Dík

**Comment by sinacek** [comment]
Ahoj,
díky za podnět, bohužel to nestíhám tedka tam dát pořádně do kupy, ale
pokud to potřebuješ, tak ti může pomoci wiki
https://github.com/sinacek/SkautIS/wiki/Tutorial . Jinak o tom vím, že to
je můj kostlivec ve skříni...

Sin

Dne 7. dubna 2013 23:57 Pavel Zbytovský notifications@github.comnapsal(a):

**Comment by zbycz** [comment]
jůů, to je přesně ono, dobrá práce! Potřebuju totiž jen přihlášení. Nějak mě nenapadlo rozklikávat wiki, když chybělo to README

Takovéhle kostlivce bych chtěl mít taky :-)
