### ISSUE TITLE
Notice: Array to string conversion as WS.php:92

### ISSUE THREAD

**Issue by patrickkusebauch** [skaut/Skautis#34]
Verze systémů:
- SkautIS - forr z repo dne 22.12.2014
- Nette - 2.2.3 revize 2014-08-28

Popis problému:
Snažím se rozjet SkautIS podle dokumentace (co jsem kde poshrabával místama), avšak narážím na následující problém při použití tohoto kusu kódu z readme.md:

``` php
$data = $skautis->user->UserDetail(array("ID"=>1940));
```

Vyhodí to v Nette vyjímku :"Notice: Array to string conversion as WS.php:92"

Kód okolo toho:

``` php
class SkautisPresenter extends BasePresenter
{
    /** @var  \SkautIS\SkautIS */
    protected $skautIS;

    /**
     * Injects connection to IS skaut
     *
     * @param \SkautIS\SkautIS $skautIS
     * @throws \Nette\InvalidStateException
     */
    public function injectEvent(\SkautIS\SkautIS $skautIS){
        if ($this->skautIS) {
            throw new \Nette\InvalidStateException('SkautIS has already been set');
        }
        $this->skautIS = $skautIS;
    }

    public function actionDefault(){
        $request = $this->request;
        if ($request->getPost('skautIS_Token')
            && $request->getPost('skautIS_IDRole')
            && $request->getPost('skautIS_IDUnit')
        ){
            $this->skautIS->setLoginData($request->getPost('skautIS_Token')
                ,$request->getPost('skautIS_IDRole')
                ,$request->getPost('skautIS_IDUnit'));
        } elseif ($this->skautIS->isLoggedIn()){
            $this->skautIS->updateLogoutTime();
        } else {
            $this->redirect('login');
        }
    }

    public function renderDefault(){
        $this->skautIS->getWsdlList();
        $this->template->person = $this->skautIS->user->UserDetail(array("ID"=>1940));
    }
    /**
     * Sets variable for view of "Default" page
     */
    public function renderLogin()
    {
        $this->template->loginUrl = $this->skautIS->getLoginUrl();
    }
```

Účelem je vážně jen nějaké řešení, které začne tahat opravdová data, abych se měl od čeho odpíchnout.

**Comment by sinacek** [comment]
Ahoj,
ze které větve jsi to použil? Zatím určitě používej verze 1.x a tam by mělo být vše vpohodě. Nová verze 2.x je hodně ve vývoji. Případně mi pošli celý projekt v zipu a já to zkusím u sebe.(sinacek@skaut.cz)

**Comment by patrickkusebauch** [comment]
Z větve 1.x jelikož je označená jako master/default.

**Comment by sinacek** [comment]
A poslal by jsi mi tvůj projekt? Já jsem s tímhle problém neměl.

**Comment by patrickkusebauch** [comment]
V tom případě by se hodil do dokumentace nástřel funkčního presenteru na místo jednoho řádku kódu jako příklad použití. Kód bundluju a posílám...

**Comment by patrickkusebauch** [comment]
Po delším dumání a zkoumání laděnky jsem dospěl k závěru, že error způsobuje tento řádek 

``` php
        } elseif ($this->skautIS->isLoggedIn()){
```

Zdá se, že že ISskaut vyžaduje, aby parametry byly řetezce a ne pole. Což ale nedává smysl, protože podle SOAP dokumentace tomu tak rozhodně není.
