### ISSUE TITLE
Coding style 

### ISSUE THREAD

**Issue by JindrichPilar** [skaut/Skautis#36]
Jelikoz se codebase rozrusta, je potreba rozhodnout o cofing style. Idealne mit i config pro [PHP Code Sniffer](https://github.com/squizlabs/PHP_CodeSniffer) / [PHP Code Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer).

Projekty pro urcity framework by meli pouzivat veci zabehle pro dany framework, takze se jedna hlavne o samostatnou knihovnu.

Krome stylu psani je potreba rozhodnout i o jednotnem pojmenovani.
Napriklad:
`ISessionAdapter` vs `SessionAdapterInterface`
`ASessionAdapter` vs `AbstractSessionAdapter`

Jako vyhodu delsiho zapisu vidim ze kazdy to muze precist bez znalosti toho prefixovani pismenem. Take mi prijde v PHP komunite rozsirenejsi ([Symfony](http://symfony.com/doc/current/contributing/code/standards.html#naming-conventions), [Zend 2](http://framework.zend.com/wiki/display/ZFDEV2/Coding+Standards#CodingStandards-AbstractClasses))

Nejlehci by bylo prevzit to od nejakeho projektu, jelikoz bychom nemuseli sepisovat pravidla a vytvaret config pro PHP Code Sniffer.

Takhle vypadaji nejake statistiky vuci PSR2.

**Comment by xificurk** [comment]
Ad pojmenování - taky myslím, že bude lepší držet delší názvy. Obecně asi nemá smysl měnit bez dobrých důvodů již zaběhlé konvence.

**Comment by xificurk** [comment]
Ještě bych teda na seznam věcí k rozhodnutí přidal uspořádání tříd výjimek - současný stav se mi moc nelíbí. Vím, že se celkem často takto používá samostatný namespace pro výjimky, ale přijde mi, že jediný (dost špatným) důvodem, proč to tak dělat, je kompatibilita s PSR-4.
Třeba tohle se mi líbí a používá daleko lépe:
https://github.com/Kdyby/Curl/blob/master/src/Kdyby/Curl/exceptions.php

**Comment by JindrichPilar** [comment]
Osobne se mi libi class per file pristup. Taky by byla moznost presunout z hromadneho namespacu pro vsechny exception k tomu k cemu se vztahuji. Mam pocit ze po zmenach ktere probehly tam jsou i vyjimky ktere se nikde nepouzivaji.

**Comment by xificurk** [comment]
Ano, class per file je dobrý, ale zrovna ty výjimky docela výjimkou :-)
Osobně mi přijde jako nejlepší umístění přímo namespace `Skautis` (příp. nějaký sub-namespace, ale nevím jestli to tady má smysl). A celý ten odkazovaný pattern, kdy existuje interface `Foo\Exception`, jednotlivé výjimky pak dědí od odpovídajících standardních PHP výjimek a všechny implementují `Foo\Exception`, aby se daly hromadně odchytnout všechny výjimky z balíku `Foo`.
A tady potom naráží ten class per file přístup, protože se ti kořenový adresář zaplevelí spoustou souborů výjimek, které ještě k tomu povětšinou obsahují jen deklaraci třídy a nic víc.
