### ISSUE TITLE
composer package

### ISSUE THREAD

**Issue by JindrichPilar** [skaut/Skautis#4]
Ahoj,

navrhuji doplnit možnost instalace pomocí composer + packagist (http://getcomposer.org/)

Velmi usnadňuje práci se závislostmi + class autoloading. 
Je velmi využívaný např.:  Drupal (8), phpBB, a naprostá většina frameworků Nette, Symfony, Zend, Laravel..

Pokud by o to byl zájem, rád to udělám a hodím pull request.

**Comment by sinacek** [comment]
Ahoj,
jsem určitě pro, tak jestli mi to hodíš pull request, tak ho rád přidám.

**Comment by JindrichPilar** [comment]
Ahoj,

připravil jsem k prohlédnutí 2 verze.

a) jen composer (https://github.com/jinora/SkautIS/tree/composer_package)
b) composer + namespace (https://github.com/jinora/SkautIS/tree/dev-master)

Osobne preferuji variantu b), je více podobná běžným frameworkům a knihovnám, takže se člověk snáze přesouvá z jedné části kodu do druhe + snazší pro úpravy a rozšíření.

**Comment by sinacek** [comment]
Namespace jsem tam nedával, aby to začínající programátory neodradilo, že to neznají a neví jak s tím pracovat, proto bych raději ještě zůstal nějaký čas bez nich. Vidíš v přidání namespace výrazné výhody?

**Comment by JindrichPilar** [comment]
Jak se to vezme, samy o sobě "jen" zpřehledňují strukturu kodu.  Pro plain PHP aplikaci psanou úplným začátečníkem nebudou mít velký přínos. (ale myslím si že ho spíš zmate SOAP)

Větší přínosy vidím při integraci do větších systémů (CMS, nebo vlastni app s frameworkem) a nebo při případném rozšiřování knihovny. A to kvůli jednotnosti struktury kodu. Většina knihoven používá autoloading založený na namespace (PS-0) a tedy i striktní strukturu souborů. 

Ovšem takhle velká knihovna určitě nemá problém se obejít bez namespace. Spíš jde o to nastavit kvůli zpětné kompatibilitě jednotný přístup. A pokud by se měla knihovna v budoucnu rozšiřovat a měly na ní záviset různé pluginy do CMS apod. Preferoval bych namespace.

**Comment by sinacek** [comment]
Jo takle, tak dobrá, pošli mi prosím pull request s composerem a s namespace a já to tam přihodím. A když si někdo nebude vedět rady, tak mi napíše.

**Comment by sinacek** [comment]
Je to tam, díky za přispění a vylepšení

**Comment by JindrichPilar** [comment]
Není zač. Ještě je potřeba abys přidal tenhle repozitář  na packagist.org a composer věděl odkud má knihovnu instalovat.

**Comment by sinacek** [comment]
Můžeš to prosím zkontrolovat, jestli jsem to přidal správně?

**Comment by JindrichPilar** [comment]
Vyzkoušel jsem a funguje správně.
