### ISSUE TITLE
Nevhodně se chovajíci isMaintenance při nenalezení domeny

### ISSUE THREAD

**Issue by JindrichPilar** [skaut/Skautis#57]
Když se pokusí `isMaintenance` získat headery Skautisu a serveru se nepodaří DNS lookup tak hodí warning:

``` PHP
Warning: get_headers(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
```

Což podle toho jak aplikace řeší warningy může znamenat že se bude ignorovat, nebo třeba že se bude považovat za error a aplikace vrátí "Něco se rozbilo" místo toho aby prostě vypnula Skautis funkce a dál fungovala.
Osobně nechápu proč je tohle řešeno přes warning a ne exception. 

Možné řešení:

``` php
        set_error_handler(function() {});
        $headers = get_headers($this->getWebServiceUrl("UserManagement"));
        restore_error_handler();

        return !is_array($headers) || !in_array('HTTP/1.1 200 OK', $headers);
```

To je nejsnazší, v případě problému se bude trvářit že Skautis je v údržbě a zbytek aplikace bude fungovat dál. Ale ztratí se informace co nešlo (DNS lookup) a metoda isMaintanance checkuje i něco co chekovat nemá.

Samozřejmě by šlo to [transformovat do exceptionu](http://stackoverflow.com/a/1241751/927443) což je o něco lepší, protože se dají hromadně chytat skautis exceptiony. Ale pořád je to nicmoc použití. Obzvláště když napojení na skautis je vedlejší funkcionalita a tedy to že se nelze připojit není problém ale je to potřeba vědět.

Př:

``` php
try {
  if (!$this->skautis->isMaintanance() {
    $this->updateUserInfoFromSkautis();
  }
}
catch (\Skautis\Exception $e) {
  //ignore nebo log
}

$this->displaySomePage();
```

**Comment by sinacek** [comment]
Tím, že jsem se s tím nikdy moc reálně nesetkal, tak nevím jaké chování bych očekával. Ale asi bych klidně volil první řešení, kde by se to dalo kontrolovat daný exception namísto pouhého function() {}.
