### ISSUE TITLE
Jméno balíčku a namespace

### ISSUE THREAD

**Issue by JindrichPilar** [skaut/Skautis#58]
Jelikož se pomalu hromadí projekty na github.com/skaut. Bylo by dobré mít věci přehledné. 
Dobrým začátkem by bylo mít společené root namespace skaut.
### Současný stav

| Repozirář | Baliček | Kvalifikovaná hlavní třída |
| :-- | :-: | :-: |
| skaut/Skautis | skautis/skautis | Skautis\Skautis |
### Navrhovaný stav

| Repozirář | Baliček | Kvalifikovaná hlavní třída |
| :-- | :-: | :-: |
| skaut/skautis | skaut/skautis | Skaut\Skautis |

**Comment by sinacek** [comment]
Projekty se hromadí, ale bojím se, že to tam stejně uplně nesjednotíme. Návrh se mi v principu líbí, ale nevím jestli to stojí za to, že to nebude zpětně kompatibilní. Protože lidi co to většinou používají, tak to někdy nasadili a kodu tolik nerozumí se obávám.
Sin

**Comment by JindrichPilar** [comment]
Je to myšlenka pro příští major verzi. Ktará se rozhodně časově neblíží. A kdoví jaké budou pak změny. Chtěl jsem to hlavně nadhodit aby to bylo na paměti v budoucnu a třeba i při zakládání nových projektů.

**Comment by sinacek** [comment]
V příští major verzi asi klidně, ale na tu jsme zatím ani nepomyslel, když vše dobře běhá

**Comment by JindrichPilar** [comment]
Jak se k teto issue stavite? Bylo by to pekne, ale prakticky prinos nepatrny - zato velky BC break.
Verze 3.0 pro PHP 7+ je asi nejvhodnejsi (nejmene nevhodna) chvile. Proto navrhuji ted, nebo issue zavrit.

(Dopad BC breaku by slo zmirnit navodem pro pouziti [Rector - RenameNamespaceRector](https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#renamenamespacerector)

@sinacek @fmasa

**Comment by fmasa** [comment]
@JindrichPilar + Je to otázka jednoduchýho search&replace, takže je to jednoduše fixnutelný - šel bych do toho.

**Comment by sinacek** [comment]
jsem pro to změnit jak píšeš společně s PHP7 a nette 3

**Comment by marekdedic** [comment]
A https://packagist.org/packages/skautis/nette a https://packagist.org/packages/skautis/nette-unit-info by taky byly přejmenovaný?
