### ISSUE TITLE
Nefunkční odkaz v dokumentaci

### ISSUE THREAD

**Issue by marekdedic** [skaut/Skautis#63]
Druhý odkaz v docs/pouziti.md nefunguje (http://test-is.skaut.cz/JunakWebservice/). Nejsem si jist, ale myslím, že správná adresa by mohla být http://is.skaut.cz/napoveda/programatori.webservice.ashx.

**Comment by JindrichPilar** [comment]
Me funguje, akorat me presmeruje na HTTPS protokol. Spravne ma byt https://test-is.skaut.cz/JunakWebservice/.

Muzes prosim popsat co to dela tobe?

**Comment by marekdedic** [comment]
Aha, když tam ručně připíšu https, tak mi to taky funguje. Jinak to hodí 404.

**Comment by sinacek** [comment]
Opraveno https://github.com/skaut/Skautis/commit/10f42c5d128feb2d04d330d3ce19f6af2ca4f2db
