### ISSUE TITLE
Nahradit vlastni CacheInterface za PSR cache

### ISSUE THREAD

**Issue by JindrichPilar** [skaut/Skautis#69]
Navrhuji odstranit vlastni interface pro cache a pouzit [PSR cache](https://www.php-fig.org/psr/psr-6/) Vetsina frameworku toto interface implementuji, nebo k nim existuje bridge - [Symfony](https://symfony.com/blog/new-in-symfony-3-1-cache-component).

**Comment by fmasa** [comment]
Doporučuju kdyžtak sáhnout po [PSR-16](https://www.php-fig.org/psr/psr-16/), má širší podporu, protože nabízí jednodušší API
