### ISSUE TITLE
setInit

### ISSUE THREAD

**Issue by MilanLochovsky** [skaut/Skautis#7]
V nápovědě se píše o funkci setInit, ale nikde jsem ji nedohledal...

**Comment by sinacek** [comment]
Chyba v dokumentaci, už jsem to v ni upravil, doporučený postup je to nastavit přes 3 settery.

**Comment by MilanLochovsky** [comment]
Jj :) Přesně takhle jsem to udělal. Jen aby příště někdo nemusel zkoumat jako já, ;) Děkuji!
