### ISSUE TITLE
Chyba parseOutput

### ISSUE THREAD

**Issue by jan-stanek** [skaut/Skautis#90]
Ve verzi 3.0.0 alpha 1 je problém s parsováním output, pokud neobsahuje tag <...Output> - např.: 
> Undefined property: stdClass::$UserDetailOutput

Další problém je v typu, pokud se vrací $result (stdClass místo array)

```
...
$output = $result->{$fname . 'Output'};
if (!isset($output)) {
    return $result; //neobsahuje $fname.Output
}
...
```

**Comment by fmasa** [comment]
> Další problém je v typu, pokud se vrací $result (stdClass místo array)

Máš na mysli situaci, kdy prázdný výsledek vrací prázdnou `stdClass` místo pole, nebo něco jiného? To by každopádně stálo za to také opravit. Takhle je potřeba [všude kontrolovat, že se nevrátila prázdná `stdClass` místo pole](https://github.com/skaut/Skautske-hospodareni/blob/master/app/model/Skautis/UnitRepository.php#L33)

**Comment by jan-stanek** [comment]
Tady: https://github.com/skaut/Skautis/blob/48a2e95d10179844c65d2bc758100fb16679a117/src/Wsdl/WebService.php#L163

Zatím jsem neměl čas zjistit, jestli stačí změnit na `return [$result];`

**Comment by JindrichPilar** [comment]
@jan-stanek Děkuji za vyzkoušení alpha verze a za bug report.

**Comment by JindrichPilar** [comment]
@jan-stanek  https://github.com/skaut/Skautis/pull/91 byl mergnut a vydal jsem [`v3.0.0-alpha.2`](https://github.com/skaut/Skautis/releases/tag/v3.0.0-alpha.2). Tím by tato issue měla být vyřešena.

**Comment by sinacek** [comment]
@JindrichPilar @jan-stanek Můžu to tady zavřít a vydáme 3.0, nastavím to jako default branch?

**Comment by jan-stanek** [comment]
teď už si vůbec nevzpomínám, u SRS používáme pořád 2.x, můžu večer zkusit přepnout

**Comment by jan-stanek** [comment]
@sinacek tak nakonec jsem to nevyzkoušel, protože skautis/nette vyžaduje alpha 1, budeš dělat release i u něj?

**Comment by sinacek** [comment]
> @sinacek tak nakonec jsem to nevyzkoušel, protože skautis/nette vyžaduje alpha 1, budeš dělat release i u něj?

udělal jsem https://github.com/skaut/SkautisNette/releases/tag/v3.0.0-alpha.1

**Comment by JindrichPilar** [comment]
@sinacek 

> vydáme 3.0, nastavím to jako default branch?

S 3.0 cekam na https://github.com/skaut/Skautis/issues/97, aby v byla v `WebServiceInterface` metoda vracejici promise.
Nevim jak na tom @fmasa je, chtel se do toho pustit.

**Comment by jan-stanek** [comment]
skautis/nette pořád závisí na skautis/skautis 3.0.0.alpha.1, ne 3.0.0.alpha.2, stáhnul jsem to ručně, ale skautis/nette s tím není kompatibilní - mezi 3.0.0.alpha.1 a 3.0.0.alpha.2 se měnily namespacy

**Comment by sinacek** [comment]
> skautis/nette pořád závisí na skautis/skautis 3.0.0.alpha.1, ne 3.0.0.alpha.2, stáhnul jsem to ručně, ale skautis/nette s tím není kompatibilní - mezi 3.0.0.alpha.1 a 3.0.0.alpha.2 se měnily namespacy

Tak ono těch změn tak je více než jen namespacy a to teďka rychle neupravím :/

**Comment by jan-stanek** [comment]
vydány nové verze skautisnette i skautis, které jsou mezi sebou kompatibilní a obsahují #91
