### ISSUE TITLE
Kompatibilita s PHP 8.1

### ISSUE THREAD

**Issue by jan-stanek** [skaut/Skautis#99]
Verze 2.x i 3.x používají interface `Serializable`, který je deprecated v PHP 8.1: https://php.watch/versions/8.1/serializable-deprecated

**Comment by JindrichPilar** [comment]
Ahoj, diky za report. https://github.com/skaut/Skautis/pull/100 by to mel vyresit pro 3.x.

**Comment by jan-stanek** [comment]
Vyřešeno
